[package]
name = "kalman_filter_3d"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.32.3", features = ["rand"] }
rand = "0.8.5"
plotters = "0.3.5"
csv = "1.3"
clap = { version = "4.5", features = ["derive"] }
